/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package universidadgrupo4.vistas;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import universidadgrupo4.control.CursadaData;
import universidadgrupo4.control.MateriaData;
import universidadgrupo4.modelos.Alumno;
import universidadgrupo4.modelos.Conexion;
import universidadgrupo4.modelos.Cursada;
import universidadgrupo4.modelos.Materia;
import static universidadgrupo4.vistas.ViewAlumno.validarString;

/**
 *
 * @author Maxi
 */
public class ViewMateria extends javax.swing.JInternalFrame {

    Conexion con;
    
    public ViewMateria(Conexion conexion) {
        initComponents();
        con = conexion;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtId = new javax.swing.JTextField();
        jtAño = new javax.swing.JTextField();
        jbBuscar = new javax.swing.JButton();
        jbGuardar = new javax.swing.JButton();
        jbBaja = new javax.swing.JButton();
        jbActualizar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jtNombre = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        chActivo = new javax.swing.JCheckBox();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 102, 255));
        jLabel1.setText("Materias");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel2.setText("NOMBRE");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel3.setText("ID");

        jtId.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        jtId.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtIdMouseClicked(evt);
            }
        });

        jtAño.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        jtAño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtAñoActionPerformed(evt);
            }
        });

        jbBuscar.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        jbBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lupa2.png"))); // NOI18N
        jbBuscar.setText("Buscar");
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });

        jbGuardar.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        jbGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/guardar.png"))); // NOI18N
        jbGuardar.setText("Guardar");
        jbGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGuardarActionPerformed(evt);
            }
        });

        jbBaja.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        jbBaja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancelar.png"))); // NOI18N
        jbBaja.setText("Baja");
        jbBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBajaActionPerformed(evt);
            }
        });

        jbActualizar.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        jbActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/actuaizar.png"))); // NOI18N
        jbActualizar.setText("Actualizar");
        jbActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbActualizarActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel4.setText("AÑO");

        jtNombre.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        jtNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtNombreFocusGained(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel9.setText("ESTADO:");

        chActivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chActivoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(254, 254, 254))
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jtId, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(364, 364, 364)
                        .addComponent(jbBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbGuardar)
                                .addGap(18, 18, 18)
                                .addComponent(jbActualizar)
                                .addGap(18, 18, 18)
                                .addComponent(jbBaja))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jtAño, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(chActivo, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(14, 14, 14)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 47, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtId, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtAño, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(chActivo, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbBaja, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed
        int id=0;
        String nombre = null;
        boolean val=false;
        MateriaData nuevo = new MateriaData(con);
        Materia mat = null;
        
        try {
            id = Integer.parseInt(jtId.getText()) ;
            val=true;
            try {
            mat = nuevo.buscarMateria(id);
            jtNombre.setText(mat.getNombreMateria());
            jtAño.setText(String.valueOf(mat.getAnio()));
        } catch (NullPointerException e){
            JOptionPane.showMessageDialog(this, "No se encuentra la materia con ID: "+id);
            limpiar();
        }
        } catch (NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Campo incorrecto en ID Materia"); 
            limpiar();
            jtId.requestFocus();
        }
        
        
        
        
    }//GEN-LAST:event_jbBuscarActionPerformed

    private void jbGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGuardarActionPerformed
        String nombre = null;
        int año = 0;
        boolean val=false;
        MateriaData nuevo = new MateriaData(con);
        ArrayList <Materia> materias = new ArrayList();
        boolean estado = false; 
        
        
        if(chActivo.isSelected()){
            estado=true;
        }else{
            estado=false;
        }
        
        
        try {
            nombre = jtNombre.getText();
                if (nombre.isEmpty()){
                    JOptionPane.showMessageDialog(this, "Campo vacio en NOMBRE");
                    jtNombre.requestFocus();
                }
                else if (!validarString(nombre)){
                        JOptionPane.showMessageDialog(this, "Formato de NOMBRE incorrecto");
                        jtNombre.requestFocus();
                }
                else{
                try{
                    año = Integer.parseInt(jtAño.getText());
                    val = true;
                    
                    if(val){
                        materias = nuevo.obtenerMaterias();
                        Materia mat = new Materia(nombre,año,estado);
            
                        if (materias.stream().anyMatch(a->a.getNombreMateria()==mat.getNombreMateria())){
                            JOptionPane.showMessageDialog(this, "Ya existe la materia "+ mat.getNombreMateria()+ " en el sistema");
                            limpiar();
                        }
                        else{
                                nuevo.guardarMateria(mat);
                                JOptionPane.showMessageDialog(this, "Materia agregada");
                                limpiar();
                        }           
                    }
                }catch(NumberFormatException e){
                    JOptionPane.showMessageDialog(this, "Formato de AÑO incorrecto");
                    jtAño.requestFocus();
                }}
        }
                        
        catch(Exception e){}                   
    }//GEN-LAST:event_jbGuardarActionPerformed

    private void jbBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBajaActionPerformed
        int id=0;
        String nombre = null;
        boolean val=false;
        MateriaData nuevo = new MateriaData(con);
        Materia mat = null;
        
        try {
            id = Integer.parseInt(jtId.getText()) ;
            val=true;
            mat = nuevo.buscarMateria(id);
            if(mat==null){
                JOptionPane.showMessageDialog(this, "No se encuentr materia con ID: "+id);
                limpiar();
            }else{
               
            
            
            int opcion = JOptionPane.showConfirmDialog(this, "Esta accion dara de baja:\n " 
            + mat.toString() + 
            "\n Estas seguro?", "ATENCION", 2, JOptionPane.WARNING_MESSAGE);
            if (opcion==0) {
                nuevo.desactivarMateria(id);
                JOptionPane.showMessageDialog(this, "Materia desactivada");
                limpiar();
            }
            
            
            }
                    
                    
            
        } catch (NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Formato de ID incorrecto"); 
            limpiar();
        }
        
        
    }//GEN-LAST:event_jbBajaActionPerformed

    private void jbActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbActualizarActionPerformed
        int id=0;
        int año=0;
        String nombre = null;
        boolean val=false;
        MateriaData nuevo = new MateriaData(con);
        boolean estado = false;
        CursadaData cd = new CursadaData(con);
        ArrayList<Cursada> cursadas = (ArrayList<Cursada>) cd.obtenerCursadas();
        
        
        if(chActivo.isSelected()){
            estado=true;
        }else{
            estado=false;
        }
        
        try {
            nombre = jtNombre.getText();
            año = Integer.parseInt(jtAño.getText()) ;
            id = Integer.parseInt(jtId.getText());
            val=true;
        } catch (NumberFormatException e){}
        if (nombre.isEmpty()||val==false){
           JOptionPane.showMessageDialog(this, "Campo incorrecto"); 
           limpiar();
        }else{
            if (nuevo.buscarMateria(id)==null) {
                  JOptionPane.showMessageDialog(this, "No se encuentra la materia con ID: "+id);
                  limpiar();      
                  
            }else{
                
                Materia mat = new Materia(id,nombre,año,estado);            
                int opcion = JOptionPane.showConfirmDialog(this, "Esta seguro que desea modificar:\n " 
                + nuevo.buscarMateria(id).toString(), "ATENCION", 2, JOptionPane.WARNING_MESSAGE);
                    if (opcion==0) {
                        nuevo.actualizarMateria(mat, id);
                        JOptionPane.showMessageDialog(this, "Se ha modificado la materia");
                        limpiar();
                    }
                }
            }
        
    }//GEN-LAST:event_jbActualizarActionPerformed

    private void jtAñoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtAñoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtAñoActionPerformed

    private void chActivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chActivoActionPerformed

    }//GEN-LAST:event_chActivoActionPerformed

    private void jtIdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtIdMouseClicked
       jtId.setEditable(true);
       jtId.setBackground(Color.WHITE);
       jtNombre.setEditable(false);
       jtAño.setEditable(false);
       
       jtNombre.setBackground(Color.LIGHT_GRAY);
       jtAño.setBackground(Color.LIGHT_GRAY);
       
    }//GEN-LAST:event_jtIdMouseClicked

    private void jtNombreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtNombreFocusGained
       boolean val = true;
       jtId.setEditable(false);
       jtId.setBackground(Color.LIGHT_GRAY);
       jtNombre.setEditable(val);
       jtAño.setEditable(val);
       jtNombre.setBackground(Color.WHITE);
       jtAño.setBackground(Color.WHITE);
    }//GEN-LAST:event_jtNombreFocusGained


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chActivo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton jbActualizar;
    private javax.swing.JButton jbBaja;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JButton jbGuardar;
    private javax.swing.JTextField jtAño;
    private javax.swing.JTextField jtId;
    private javax.swing.JTextField jtNombre;
    // End of variables declaration//GEN-END:variables
private void limpiar()
    {
        jtId.setText("");
       jtAño.setText("");
       jtNombre.setText(""); 
    }
public static boolean validarString(String user){
    String specialChars = "~`!@#$%^&*()-_=+\\|[{]};:'\",<.>/?";
        boolean specialchar = false;
        boolean numero = false;
            for (int i = 0; i < user.length(); i++) {
                if (specialChars.contains(String.valueOf(user.charAt(i)))) {
                    specialchar = true;
                } else if (Character.isDigit(Integer.valueOf(user.charAt(i)))) {
                    numero = true;
                }
            }
            if (specialchar || numero) {
                return false;
            } else {
                return true;
            }
        }
    


private static boolean isNumeric(String cadena){
	try {
		Integer.parseInt(cadena);
		return true;
	} catch (NumberFormatException nfe){
		return false;
	}
}
}
